export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <>
  <h1>New Layout for AUTH</h1>
      {children}
      
      </>
  )
}
