import React from 'react';

interface LayoutProps {
  first: React.ReactNode;
  second: React.ReactNode;
}

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};

const RootLayout: React.FC<LayoutProps> = ({ first, second }) => {
  return (
    <>
      <h1>New Layout for AUTH</h1>
      {first}
      {second}
    </>
  );
};

export default RootLayout;
