export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <header
      style = {{
        backgroundColor: "skyblue",
        padding: "1rem"
      }}
      >
        <h1>Header</h1>
      </header>
      {children}
      <footer style = {{
        backgroundColor: "ghostwhite",
        padding: "1rem"
      }}><h1>Footer</h1></footer>
      </body>
      
    </html>
  )
}
